
export enum ErrorType {
  WAIT = "WAIT",
  CLICK = "CLICK",
  FILL = "FILL",
  KEYBOARD = "KEYBOARD",
  MOUSE = "MOUSE",
  DROPDOWN = "DROPDOWN",
  UPLOAD = "UPLOAD",
  DATE_PICKER = "DATE_PICKER",
  TABLE = "TABLE",
  FRAMEWORK = "FRAMEWORK",
  ASSERTION = "ASSERTION",
  API = "API",
  DATABASE = "DATABASE",
  UNKNOWN = "UNKNOWN"
}