export enum ActionNames {
    KEYBOARD_PRESS = "KeyboardHelper.press",
    KEYBOARD_TYPE = "KeyboardHelper.type",
    KEYBOARD_COMBINATION = "KeyboardHelper.pressCombination",
    KEYBOARD_SLOW_TYPE = "KeyboardHelper.typeSlowly",

    CLICK = "ClickHelper.click",
    FILL = "FillHelper.fill",

    ASSERT_VISIBLE = "AssertHelper.visible",
    ASSERT_HIDDEN = "AssertHelper.hidden",
    ASSERT_TEXT = "AssertHelper.text",
    ASSERT_VALUE = "AssertHelper.value",
    ASSERT_ENABLED = "AssertHelper.enabled",
    ASSERT_DISABLED = "AssertHelper.disabled",
    ASSERT_CHECKED = "AssertHelper.checked",
    ASSERT_UNCHECKED = "AssertHelper.unChecked",
    ASSERT_URL = "AssertHelper.url",
    ASSERT_TITLE = "AssertHelper.title",

    MOUSE_HOVER = "MouseHelper.hover",
    MOUSE_DOUBLE_CLICK = "MouseHelper.doubleClick",
    MOUSE_RIGHT_CLICK = "MouseHelper.rightClick",
    MOUSE_DRAG_AND_DROP = "MouseHelper.dragAndDrop",
    MOUSE_MOVE = "MouseHelper.move",
    MOUSE_DOWN = "MouseHelper.mouseDown",
    MOUSE_UP = "MouseHelper.mouseUp",
    MOUSE_WHEEL = "MouseHelper.mouseWheel",

    DROPDOWN_SELECT_TEXT = "DropdownHelper.selectByText",
    DROPDOWN_SELECT_VALUE = "DropdownHelper.selectByValue",
    DROPDOWN_SELECT_LABEL = "DropdownHelper.selectByLabel",
    DROPDOWN_SEARCH = "DropdownHelper.selectSearchable",
    DROPDOWN_MULTI = "DropdownHelper.selectMulti",

    CHECKBOX_CHECK = "CheckboxHelper.check",
    CHECKBOX_UNCHECK = "CheckboxHelper.uncheck",
    CHECKBOX_SET_CHECKED = "CheckboxHelper.setChecked",
    CHECKBOX_TOGGLE = "CheckboxHelper.toggle",
    CHECKBOX_IS_CHECKED = "CheckboxHelper.isChecked",

    RADIO_SELECT = "RadioHelper.select",
    RADIO_IS_SELECTED = "RadioHelper.isSelected",

    FILE_UPLOAD = "FileUploadHelper.upload",
    FILE_UPLOAD_MULTIPLE = "FileUploadHelper.uploadMultiple",
    FILE_UPLOAD_CLEAR = "FileUploadHelper.clear",

    NAVIGATION_GOTO = "NavigationHelper.goto",
    NAVIGATION_RELOAD = "NavigationHelper.reload",
    NAVIGATION_BACK = "NavigationHelper.goBack",
    NAVIGATION_FORWARD = "NavigationHelper.goForward",
    NAVIGATION_WAIT_FOR_URL = "NavigationHelper.waitForUrl",
    NAVIGATION_CURRENT_URL = "NavigationHelper.getCurrentUrl",

    MODAL_VISIBLE = "ModalHelper.waitForVisible",
    MODAL_HIDDEN = "ModalHelper.waitForHidden",
    MODAL_CONFIRM = "ModalHelper.confirm",
    MODAL_CANCEL = "ModalHelper.cancel",
    MODAL_MESSAGE = "ModalHelper.getMessage",
    MODAL_IS_VISIBLE = "ModalHelper.isVisible",

    TABLE_ROWS = "TableHelper.rows",
    TABLE_ROW_COUNT = "TableHelper.rowCount",
    TABLE_FIND_ROW = "TableHelper.findRow",
    TABLE_CLICK_ROW_ACTION = "TableHelper.clickRowAction",
    TABLE_GET_CELL_TEXT = "TableHelper.getCellText",
    TABLE_GET_ALL_ROWS = "TableHelper.getAllRows",
}